### ISSUE TITLE
Plugin view doesn't change 

### ISSUE THREAD

**Issue by maltisch** [featdd/dpn_glossary#94] opened 2017-06-22 13:09 UTC
Plugin view doesn't change with TYPO3 7.6.18 and glossary 2.7.3. 
Following steps has to be done:

Insert "Glossary List" Plugin on page
List of glossary terms is shown depending on listmode
Change Plugin to "Glossary preview list" 
Glossary preview list is shown
Chang Plugin back to "Glossary List"
Nothing changed, Glossary preview list is shown again 

I have tried to delete all cache options, but have not success

**Comment by featdd** [comment] 2017-06-22 13:18
I'll have to try that out, but sounds clearly like a caching problem

**Comment by rumpfwerk** [comment] 2017-07-10 09:17
I can confirm the behaviour above (maltisch) in 8.7.1

**Comment by Hawkeye1909** [comment] 2017-08-04 15:43
Same here. The problem is that after the switch from preview to list the setting for the controller action (switchableControllerActions) is not removed from database field pi_flexform in tt_content. So the extension still uses the previously set preview action ...

**Comment by featdd** [comment] 2017-08-19 12:44
hm this seems to be a general TYPO3 issue.
If you change the plugin and it has no flexform configured it should ignore its flexform field and the switchable controller action :-/

**Comment by julianhofmann** [comment] 2017-12-15 16:14
Maybe, [subtypes_excludelist](https://docs.typo3.org/typo3cms/TCAReference/Types/TypesSubtypesExcludelist.html?highlight=subtypes_excludelist) could solve this. 
Will try it soon.

**Comment by featdd** [comment] 2018-04-19 09:09
@julianhofmann did you found out something new?

**Comment by julianhofmann** [comment] 2018-04-20 15:02
Ups... Just tested: does not solve the problem. Seems only be taken into account for displaying in BE.

New idea: Analyze ConfiguartionManager and override/manipulate the configuration?

**Comment by featdd** [comment] 2018-10-07 19:19
think this is a core problem, close this for now

**Closed by featdd** 2018-10-07 19:19 UTC
