### ISSUE TITLE
Fatal error is thrown when installed but not configured

### ISSUE THREAD

**Issue by marteb** [featdd/dpn_glossary#37] opened 2015-07-31 11:18 UTC
```
[31-Jul-2015 11:14:21 UTC] PHP Catchable fatal error:  Argument 1 passed to TYPO3\CMS\Core\Utility\GeneralUtility::removeDotsFromTS() must be of the type array, null given, called in /src/typo3conf/ext/dpn_glossary/Classes/Service/WrapperService.php on line 103 and defined in /typo3_src-6.2.14/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 1845
[31-Jul-2015 11:14:21 UTC] PHP Stack trace:
[31-Jul-2015 11:14:21 UTC] PHP   1. {main}() /typo3_src-6.2.14/index.php:0
[31-Jul-2015 11:14:21 UTC] PHP   2. require() /typo3_src-6.2.14/index.php:28
[31-Jul-2015 11:14:21 UTC] PHP   3. TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->generatePage_postProcessing() /typo3_src-6.2.14/typo3/sysext/cms/tslib/index_ts.php:216
[31-Jul-2015 11:14:21 UTC] PHP   4. TYPO3\CMS\Core\Utility\GeneralUtility::callUserFunction() /typo3_src-6.2.14/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php:3559
[31-Jul-2015 11:14:21 UTC] PHP   5. TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance() /typo3_src-6.2.14/typo3/sysext/core/Classes/Utility/GeneralUtility.php:4286
[31-Jul-2015 11:14:21 UTC] PHP   6. TYPO3\CMS\Core\Utility\GeneralUtility::instantiateClass() /typo3_src-6.2.14/typo3/sysext/core/Classes/Utility/GeneralUtility.php:4415
[31-Jul-2015 11:14:21 UTC] PHP   7. DPN\DpnGlossary\Service\WrapperService->__construct() /typo3_src-6.2.14/typo3/sysext/core/Classes/Utility/GeneralUtility.php:4433
[31-Jul-2015 11:14:21 UTC] PHP   8. TYPO3\CMS\Core\Utility\GeneralUtility::removeDotsFromTS() /src/typo3conf/ext/dpn_glossary/Classes/Service/WrapperService.php:103
```

to avoid this, check if $this->tsConfig['settings.'] is an array in WrapperService.php in line 103:

```
if (is_array($this->tsConfig['settings.'])) {	
    $this->settings = GeneralUtility::removeDotsFromTS($this->tsConfig['settings.']);
}
```

**Comment by featdd** [comment] 2015-07-31 12:05
This is strange, if you've overwritten the config with empty settings it should just return an empty array.

**Comment by featdd** [comment] 2015-08-03 09:46
couldn't reproduce this error...

**Comment by marteb** [comment] 2015-08-04 08:14
I just tried it again and i still can reproduce this error.

What i did to reproduce:

- install new, clean TYPO3 6.2.14
- set up basic typoscript template:
```
page = PAGE
page.10 = TEXT
page.10.value = HELLO WORLD!
```
- include static css_styled_content template
- NOT include static dpn_glossary template (for example, in a multisite setup, only specific sites would use dpn_glossary)

and now, the reported fatal error is thrown.

**Comment by featdd** [comment] 2015-08-04 08:24
Aaah that could be the problem, the parser is hooked in the core.
Even though there is no configuration the parser will be called but gets the error because there is no config.
I can fix this but I for the glossary to work you have to include the static template in your root template.

**Comment by marteb** [comment] 2015-08-04 08:29
Yes, sure, in a single-site setup, where the static dpn_glossary template should be included anyway when the extension is installed, it works.

But, for example, in a multi-site setup, where only 1 of 3 sites uses the extension, the sites where the static dpn_glossary template is not included will not work anymore.

**Comment by featdd** [comment] 2015-08-04 08:39
Mkay, will catch this in the parser but I can't prevent calling the parser on the other instances because of the hook.

**Comment by marteb** [comment] 2015-08-17 07:27
The bugfix is still missing in version 2.3.0, isn’t it?

**Comment by featdd** [comment] 2015-08-17 12:33
Ups, still is existent, will prepare it for 2.3.1

**Comment by featdd** [comment] 2015-08-19 09:16
fixed in ad2aba5b79203bb4ceae26bc4352565adc140787
sorry you had to wait so long

**Closed by featdd** 2015-08-19 09:16 UTC
Labels: BUGFIX

**Comment by marteb** [comment] 2015-08-19 11:08
Thank you :)

Waiting was no problem, i just patched it. Thank you for this nice glossary extension!

**Comment by marteb** [comment] 2015-08-28 07:13
Hi @featdd,

i’m sorry to comment again to this issue, but since your latest changes i can’t get the glossary working. It seems, that the new condition ```if (NULL === empty($this->tsConfig))```is always true. Even if the extension is configured.

Can you have a look at it again please? Or, if my config is wrong, tell me, how to do it right?

In my TypoScript Constants i have the following:

```
plugin.tx_dpnglossary {
	settings {
		detailPage = 508
		listPage = 409
		listmode = normal
	}
	persistence.storagePid = 507
}
```

And this was okay before the latest update…

**Comment by featdd** [comment] 2015-08-28 07:35
is the configuration added to the root template?

**Comment by marteb** [comment] 2015-08-28 07:37
Yes, it is included as static template from my own configuration extension. I’ve done it this way, because i  want to have the configuration in the code and not in the database.

**Comment by featdd** [comment] 2015-08-28 07:42
You have a provider extension?
Anyway you have to add it to your root template to let the parser get it's settings.
![bildschirmfoto 2015-08-28 um 09 40 11](https://cloud.githubusercontent.com/assets/5744734/9541516/1e523814-4d69-11e5-873b-87232939f258.png)

**Comment by marteb** [comment] 2015-08-28 07:52
Yes, that’s the way i have done it as well.

In your example, the configuration would be in the Theme provider extension.

**Comment by featdd** [comment] 2015-08-28 07:58
never tried it out, would be bad practice anyway to write pageuids in your provider ext conf

**Comment by marteb** [comment] 2015-08-28 08:04
Hm, i now tried to put it in the root template, but i can’t get it to work this way either. Do you have a slack account?

**Comment by featdd** [comment] 2015-08-28 08:13
nope I'm oldschool, you can get me on irc freenode #typo3

**Comment by marteb** [comment] 2015-08-28 14:26
See https://github.com/featdd/dpn_glossary/commit/ad2aba5b79203bb4ceae26bc4352565adc140787#diff-d8dbfd2704dc56b8c46b727c78b86d80R103

and http://php.net/manual/de/function.empty.php

**Comment by featdd** [comment] 2015-08-28 14:45
oh f**k, will fix this immediately!

**Comment by featdd** [comment] 2015-08-28 14:51
Update uploaded to TER!
