### ISSUE TITLE
Problem with the character for less than (<)

### ISSUE THREAD

**Issue by metiny** [featdd/dpn_glossary#81] opened 2017-03-04 14:16 UTC
Hi Daniel,

if the character for less than (<) appears in a paragraph, one or more following words disappear in the FE. In some installations the rest of the paragraph disappear.

It only happens if there is a term in the paragraph, which is in the glossary.

I tested it with different installations:
all with TYPO3 7.6.16, 
css_styled_content / fluid_styled_content, 
PHP 5 or 7
rtehtmlarea, htmlArea RTE 7.6.0

dpn_glossary 2.6.11

**Comment by featdd** [comment] 2017-03-04 16:49
hm tried It out, but have no clue what the problem is yet.
Maybe seems to be some problem in the dom document, rte converts the character automaticly in html special chars but If I debug dom uses the real character.

have to make some investigatements

**Comment by featdd** [comment] 2017-03-05 15:02
Hi @metiny you gave me a good hint, this behavior was caused by an improper extraction of a dom nodes value.

I learned that using nodeValue directly converts html special chars, the proper way is to pass the child to the saveHtml method of the root dom document.

fixed in 0af6d5e050e1b134da6825ea563211b543da32a0

will push an update today, so will be in 2.6.12

**Closed by featdd** 2017-03-05 15:02 UTC
