### ISSUE TITLE
Problems with getting speaking URLs

### ISSUE THREAD

**Issue by martinschoene** [featdd/dpn_glossary#160] opened 2020-12-15 12:42 UTC
hi,
after adding these lines to my siteconfig:
```
PageTypeSuffix:   
    type: PageType
    default: /
    index: ''
    map:
      /: 0
```
i am getting the following error:

`Oops, an error occurred! Code: 202012151248435f9e6a74 - {"exception":"Symfony\\Component\\Routing\\Exception\\InvalidParameterException: Parameter \"t3be3391e96edf93e3ad4c195a24a51\" for route \"tx_dpnglossary_glossary_0\" must match \".+\" (\"\" given) to generate a corresponding URL......`

before adding the PageTypeSuffix, it works perfectly

TYPO3 10.4.10
dpn_glossary 3.1.6

greetings martin

**Comment by featdd** [comment] 2020-12-15 15:03
Hi @martinschoene,

could you try this:

```
PageTypes:
  type: PageType
  default: /
  index: ''
  map:
    /: 0
```

Greetings
Daniel

**Comment by martinschoene** [comment] 2020-12-16 07:38
hi @featdd,

i got the same error, when i replace my settings with yours.

greetings
martin

**Comment by featdd** [comment] 2021-04-17 15:48
Hi @martinschoene,

do you still have this issue?

I'm having issues to reproduce your error, there has also been a general issue with trailing slashes in routing.
I know it's not a proper solution but its okay to switch to urls without trailing slashes.

Greetings
Daniel

**Comment by martinschoene** [comment] 2021-05-06 13:23
Hi,

yes we had this issues with trailing slashes and because of our customer we
are forced to use trailing slashes.
So we decided not to use dpn_glossary.

greetings
Martin

**Comment by featdd** [comment] 2021-05-06 17:12
Hi @martinschoene,

sorry I couldn't help, I think the issue does not really depend on this extension.
As I'm unable to reproduce this I would close the issue for now.

If you have other problems or questions feel free to open a new issue.

Greetings
Daniel

**Closed by featdd** 2021-05-06 17:12 UTC
