### ISSUE TITLE
Empty character when first term starts with an umlaut

### ISSUE THREAD

**Issue by lkreitz** [featdd/dpn_glossary#162] opened 2021-07-15 07:29 UTC
Hi, when i open the glossary the first term in my list is used to call the pagination with it's first character by default. My first term starts with an umlaut "Ä". If this is the case the indexAction of the PaginationController returns an empty character and no terms are shown for character "A".
I found the issue on line 132 of the PaginateController:
`$firstObject[0]->{$getter}()[0]`
returns the first character if it is no umlaut. But if it is an umlaut it returns ''.

**Comment by featdd** [comment] 2023-01-28 14:24
Hi @lkreitz,

I could not reproduce this in the latest version, so I'll close this.

Greetings
Daniel

**Closed by featdd** 2023-01-28 14:24 UTC
