### ISSUE TITLE
ParserService deletes bodyClass

### ISSUE THREAD

**Issue by RomanOttDuden** [featdd/dpn_glossary#126] opened 2018-10-12 11:35 UTC
TYPO3 allows to set individual body Tags like classes and additional attributes for body-Tag

DpnGlossary and here DOMDocument with $DOM->loadHTML() builds his own bodyTag

So i would prefer to save body Tag e,g,

preg_match('/<body(.*?)>/', $html, $bodyClassMatch);

And then before output after parsing
$returnHtml = ParserUtility::protectScriptsAndCommentsFromDOMReverse(
            ParserUtility::protectLinkAndSrcPathsFromDOMReverse(
                $DOM->saveHTML()
            )
        );

        $returnHtml = str_replace('<body>', $bodyClassMatch[0], $returnHtml);

        return str_replace(
            '<?xml encoding="UTF-8">',
            '',
            $returnHtml
        );

Additional information:
Problem appears especially if you have a fullcached page without COA_INT, USER_INT etc.

**Comment by featdd** [comment] 2018-10-12 16:42
Hi @Br4inbukz,

have to test this, I think DOM should parse and keep the body class.

Greetings
Daniel

**Comment by Br4inbukz** [comment] 2018-10-15 07:38
Thx a lot, perhaps it depends on libxml and php Dom Module

**Comment by Br4inbukz** [comment] 2018-10-15 12:14
DOM/XML | enabled
-- | --
DOM/XML API Version | 20031129
libxml Version | 2.7.6

**Comment by MatthiasPeltzer** [comment] 2019-02-02 09:01
Hi there. Don´t want to open a new issue. This one is fine. 
The parser also corrupts srcset-tags and closes them, so the html with dpn_glossary will be invalid.

I have TYPO3 9.5 LTS and the actual dpn_glossary running. My FluidStyledContent Image rendering looks like this. It works fine until I activate dpn_glossary. (No other Extension running)

My fluid code:

`<picture>
    <source data-srcset="{f:uri.image(image: file, cropVariant: 'default', maxWidth: 1920)}" media="(min-width: 1280px)">
    <source data-srcset="{f:uri.image(image: file, cropVariant: 'large', maxWidth: 1280)}" media="(min-width: 1024px)">
    <source data-srcset="{f:uri.image(image: file, cropVariant: 'medium', maxWidth: 1024)}" media="(min-width: 768px)">
    <source data-srcset="{f:uri.image(image: file, cropVariant: 'small', maxWidth: 768)}" media="(min-width: 0)">
    <img class="lazyload" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAcCAYAAAAjmez3AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAADVJREFUeNrszzERAAAIBCC1f+c3hJsHDegk9cHUEyIiIiIiIiIiIiIiIiIiIiIiIiIidyvAAC2aAzXI+" data-src="{f:uri.image(image: file, cropVariant: 'default', maxWidth: 1920)}" width="{dimensions.width}" height="{dimensions.height}" alt="{file.alternative}" title="{file.title}">
</picture>`

after this, dpn_glossary adds four </source> closing tags after the last source-tag in the frontend-code.

**Comment by featdd** [comment] 2019-02-02 13:51
Hi @MatthiasPeltzer 

I googled a bit around and could not find any related issues or options for this, will have to investigate further...

PHP DOM is a complex Tool but this is not the first case it breaks some html.

Earlier I had the issue that inline javascript was altered, had to protect script tags by save them as base64 during the parsing...

If you know more than me please let me know

**Comment by featdd** [comment] 2019-06-14 19:05
Hi @MatthiasPeltzer,

there was a pull request solving this issue, I implemented a smaller solution, see here (#138)

**Comment by featdd** [comment] 2019-06-14 19:06
Hi @RomanOttDuden,

I tested this and could not reproduce this in the current version in TYPO3 9.5.

**Closed by featdd** 2019-06-14 19:06 UTC
