### ISSUE TITLE
routing

### ISSUE THREAD

**Issue by hempelta** [featdd/dpn_glossary#159] opened 2020-10-26 07:03 UTC
Hello,

i have a problem with url_segment of terms. In the backend it only shows "https://project.ddev.site:443" but not "https://project.ddev.site:443/glossar/begriff". The term is parsed in the frontend, but the link only points to "https://project.ddev.site:443#myTerm". 

Can you help me?

my config

pid 67 insert plugin dpnglossary_glossary with stroage pid 67 and recursive = 0

```
plugin.tx_dpnglossary {
    persistence {
        storagePid = 67
    }
    settings {
        addStylesheet = 0
        detailPage = 67
        previewmode = pagination
        pagination {
            characters = A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z
            insertAbove = 1
            insertBelow = 1
        }
    }
}
```

```
TCEFORM {
    tx_dpnglossary_domain_model_term {
        url_segment.config.previewUrl.pageUid = 67
    }
}
```

```
routeEnhancers:
  DpnGlossary:
    type: Extbase
    limitToPages: 67
    extension: DpnGlossary
    plugin: glossary
    routes:
      - { routePath: '/{character}', _controller: 'Term::list', _arguments: { 'character': '@widget_0/character' } }
      - { routePath: '/{localized_term}/{term_name}', _controller: 'Term::show', _arguments: { 'term_name': 'term' } }
    defaultController: 'Term::list'
    defaults:
      character: ''
    aspects:
      term_name:
        type: PersistedAliasMapper
        tableName: 'tx_dpnglossary_domain_model_term'
        routeFieldName: 'url_segment'
      character:
        type: StaticMultiRangeMapper
        ranges:
          - start: 'A'
            end: 'Z'
      localized_term:
        type: LocaleModifier
        default: 'term'
        localeMap:
          - locale: 'de_DE.*'
            value: 'begriff'
```

**Comment by featdd** [comment] 2020-10-27 18:07
Hi @hempelta,

can you check the template object browser if the TypoScript is injected properly?
Your configuration looks okay to me, an anchorlink is rendered if no detailpage is set, so I would assume the configuration is missing on the page!?

Greetings
Daniel

**Comment by hempelta** [comment] 2020-10-27 21:02
here is the template object browser
```
[tx_dpnglossary]
...
[persistence]
[storagePid] = 67
[settings]
[detailPage] = 67 # Pid of the detailpage
[parsingPids] = 0 # pages where terms should be searched, 0 = all
[parsingExcludePidList] = # pages where terms should NOT be searched
[maxReplacementPerPage] = -1 # max replacemnet per page, default = -1 (any matches)
[maxReplacementPerPageRespectSynonyms] = 0 # respect max replacement when parsing synonyms
[parsingTags] = p # Tags which content will be parsed for terms
[forbiddenParentTags] = a,script # Tags which are not allowed as direct parent for a parsingTag
[forbiddenParsingTagClasses] = # Classes which are not allowed for the parsing tag
[forbiddenParentClasses] = # Classes which are not allowed on any parent of the parsing tag
[listmode] = normal # Listmode normal or character grouped list
[previewmode] = pagination # Previewmode newest or random
[previewlimit] = 5 # Previewlimit
[disableParser] = 0 # Disable Parser option
[parseSynonyms] = 1 # Parse the terms synonyms
[priorisedSynonymParsing] = 1 # Priorise the synonyms for parsing
[useCachingFramework] = 1
[pagination]
[characters] = A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z # Pagination settings
[insertAbove] = 1
[insertBelow] = 1
[termWraps] = CASE
[addStylesheet] = 0
```

what do you mean by "the configuration is missing on the page"?

**Comment by featdd** [comment] 2020-11-01 16:16
I'm struggling to reproduce this, could you debug the ParserService and check if the settings are available?

**Comment by hempelta** [comment] 2020-11-08 15:51
I tried something ...

In my typoscript / setup / ext.dpn_glossary.typoscript is defined

plugin.tx_dpnglossary.persistence.storagePid = 67
plugin.tx_dpnglossary.settings.listmode = pagination
plugin.tx_dpnglossary.settings.detailPage = 67
plugin.tx_dpnglossary.settings.addStylesheet = 0

The last two values don't work:
plugin.tx_dpnglossary.settings.detailPage = 67
plugin.tx_dpnglossary.settings.addStylesheet = 0

storagePid and listmode works.

Result: The default CSS is also loaded and the link to the term only refers to ./#font>name of the term / field: name}, e.g. https://mysite.de/#MyTerm


If you save the following two values in the backend under template-tool at constants as follows, the links are parsed correctly and the default css is also not loaded.
plugin.tx_dpnglossary.settings.detailPage = 67
plugin.tx_dpnglossary.settings.addStylesheet = 0

Has anyone got an idea?

**Comment by featdd** [comment] 2021-04-17 15:55
Hi @hempelta,

sorry for the late response, do you still struggle with this issue?

Greetings
Daniel

**Comment by featdd** [comment] 2022-02-19 13:50
Closing this due to missing response and reproducability

**Closed by featdd** 2022-02-19 13:50 UTC
